export const INSUFFICIENT_DATA_CONFIDENCE_THRESHOLD = 0.38;
export const LOW_DATA_STRONG_SIGNAL_THRESHOLD = 0.78;
export const DISCUSSION_ORIENTED_MIN_SCORE = 0.62;
export const TOPIC_ORIENTED_MIN_SCORE = 0.62;
export const COMMUNITY_PARTICIPANT_MIN_ACTIVE_DAYS = 4;
export const COMMUNITY_PARTICIPANT_MIN_ACTIVITIES = 8;
export const COMMUNITY_PARTICIPANT_MAX_RATIO_GAP = 0.35;
export const OBSERVER_MAX_AVG_ACTIVITIES_PER_DAY = 1.5;
export const INFORMATION_CURATOR_MIN_LINK_RATIO = 0.1;
export const PROBLEM_SOLVER_MAX_QUESTION_RATIO = 0.25;

export const ARCHETYPE_PRECEDENCE = [
  'PROBLEM_SOLVER',
  'INFORMATION_CURATOR',
  'DISCUSSION_ORIENTED',
  'TOPIC_ORIENTED',
  'COMMUNITY_PARTICIPANT',
  'OBSERVER',
] as const;
