export const metricNames = {
  apiAnalyzeRequestTotal: 'api.analyze.request_total',
  apiAnalyzeRequestDurationMs: 'api.analyze.request_duration_ms',
  apiSuggestRequestTotal: 'api.suggest.request_total',
  apiSuggestRequestDurationMs: 'api.suggest.request_duration_ms',
  governanceRequestTotal: 'governance.request_total',
  governanceRequestRejectedTotal: 'governance.request_rejected_total',
  governanceRequestDegradedTotal: 'governance.request_degraded_total',
  governanceRateLimitHitTotal: 'governance.rate_limit_hit_total',
  governanceNarrativeDisabledTotal: 'governance.narrative_disabled_total',
  releaseGuardTotal: 'release.guard_total',
  releaseGuardRejectedTotal: 'release.guard_rejected_total',
  releaseGuardDegradedTotal: 'release.guard_degraded_total',
  releaseSwitchDisabledTotal: 'release.switch_disabled_total',
  releaseNarrativeForcedRuleOnlyTotal: 'release.narrative_forced_rule_only_total',
  releaseReadinessNotReadyTotal: 'release.readiness_not_ready_total',
  healthConnectorProbeTotal: 'health.connector_probe_total',
  healthConnectorProbeDurationMs: 'health.connector_probe_duration_ms',
  healthProviderProbeTotal: 'health.provider_probe_total',
  healthProviderProbeDurationMs: 'health.provider_probe_duration_ms',
  healthRuntimeCheckTotal: 'health.runtime_check_total',
  healthRuntimeCheckDurationMs: 'health.runtime_check_duration_ms',
  healthCronProbeTotal: 'health.cron_probe_total',
  connectorFetchTotal: 'connector.fetch_total',
  connectorFetchDurationMs: 'connector.fetch_duration_ms',
  connectorPartialResultTotal: 'connector.partial_result_total',
  clusterAnalysisTotal: 'cluster.analysis_total',
  clusterPartialSuccessTotal: 'cluster.partial_success_total',
  clusterAllFailedTotal: 'cluster.all_failed_total',
  clusterAccountsRequested: 'cluster.accounts_requested',
  clusterAccountsSuccessful: 'cluster.accounts_successful',
  clusterAccountsFailed: 'cluster.accounts_failed',
  clusterActivitiesDedupedTotal: 'cluster.activities_deduped_total',
  narrativeGenerateTotal: 'narrative.generate_total',
  narrativeGenerateDurationMs: 'narrative.generate_duration_ms',
  narrativeFallbackTotal: 'narrative.fallback_total',
  narrativeInvalidResponseTotal: 'narrative.invalid_response_total',
  reportComposeTotal: 'report.compose_total',
  reportComposeDurationMs: 'report.compose_duration_ms',
} as const;

export type MetricName = (typeof metricNames)[keyof typeof metricNames];
