import { z } from 'zod';

const envSchema = z.object({
  NODE_ENV: z.enum(['development', 'test', 'production']).default('development'),
  NARRATIVE_PROVIDER: z.enum(['none', 'minimax']).optional(),
  NARRATIVE_TIMEOUT_MS: z.coerce.number().int().positive().optional(),
  MINIMAX_API_KEY: z.string().optional(),
  MINIMAX_BASE_URL: z.string().optional(),
  MINIMAX_MODEL: z.string().optional(),
  FEATURE_ANALYZE_ENABLED: z.string().optional(),
  FEATURE_CLUSTER_ANALYSIS_ENABLED: z.string().optional(),
  FEATURE_SUGGEST_ENABLED: z.string().optional(),
  FEATURE_NARRATIVE_ENABLED: z.string().optional(),
  FEATURE_MINIMAX_ENABLED: z.string().optional(),
  FEATURE_HEALTH_PROBES_ENABLED: z.string().optional(),
  FEATURE_STRICT_GOVERNANCE_ENABLED: z.string().optional(),
  RELEASE_SAFETY_MODE: z.string().optional(),
  INCIDENT_ACTIVE: z.string().optional(),
  INCIDENT_SEVERITY: z.string().optional(),
  INCIDENT_REASON: z.string().optional(),
  INCIDENT_STARTED_AT: z.string().optional(),
  HEALTH_PROBE_CRON_TOKEN: z.string().optional(),
  CRON_SECRET: z.string().optional(),
});

export const env = envSchema.parse({
  NODE_ENV: process.env.NODE_ENV,
  NARRATIVE_PROVIDER: process.env.NARRATIVE_PROVIDER,
  NARRATIVE_TIMEOUT_MS: process.env.NARRATIVE_TIMEOUT_MS,
  MINIMAX_API_KEY: process.env.MINIMAX_API_KEY,
  MINIMAX_BASE_URL: process.env.MINIMAX_BASE_URL,
  MINIMAX_MODEL: process.env.MINIMAX_MODEL,
  FEATURE_ANALYZE_ENABLED: process.env.FEATURE_ANALYZE_ENABLED,
  FEATURE_CLUSTER_ANALYSIS_ENABLED: process.env.FEATURE_CLUSTER_ANALYSIS_ENABLED,
  FEATURE_SUGGEST_ENABLED: process.env.FEATURE_SUGGEST_ENABLED,
  FEATURE_NARRATIVE_ENABLED: process.env.FEATURE_NARRATIVE_ENABLED,
  FEATURE_MINIMAX_ENABLED: process.env.FEATURE_MINIMAX_ENABLED,
  FEATURE_HEALTH_PROBES_ENABLED: process.env.FEATURE_HEALTH_PROBES_ENABLED,
  FEATURE_STRICT_GOVERNANCE_ENABLED: process.env.FEATURE_STRICT_GOVERNANCE_ENABLED,
  RELEASE_SAFETY_MODE: process.env.RELEASE_SAFETY_MODE,
  INCIDENT_ACTIVE: process.env.INCIDENT_ACTIVE,
  INCIDENT_SEVERITY: process.env.INCIDENT_SEVERITY,
  INCIDENT_REASON: process.env.INCIDENT_REASON,
  INCIDENT_STARTED_AT: process.env.INCIDENT_STARTED_AT,
  HEALTH_PROBE_CRON_TOKEN: process.env.HEALTH_PROBE_CRON_TOKEN,
  CRON_SECRET: process.env.CRON_SECRET,
});
